#!/bin/bash
# MIT lizence © 2012 Waldemar Schwan
if [ -e $1 ] 
then
	time="+1"
else
	time="+$1"
fi
sudo shutdown -s $time

# this is very custom stuff
# I eject all my usb drives so I can get packing easyly after the mac went to sleep
diskutil umount /Volumes/Vergangenheit/ &
diskutil umount /Volumes/Goldshire &